const test = require('node:test')
const assert = require('node:assert/strict')
const http = require('node:http')
const { createBrokerClient, sha256, sniffImageType } = require('../lib/broker-client.cjs')

const png = Buffer.from('89504e470d0a1a0a0000000d49484452000000010000000108060000001f15c4890000000d49444154789c63600000020001e221bc33000000049454e44ae426082', 'hex')

test('desktop broker client registers, uploads bounded hashed asset, polls and reads a real result', async (t) => {
  const seen = []
  const server = http.createServer(async (request, response) => {
    const body = await new Promise((resolve) => { const chunks = []; request.on('data', (chunk) => chunks.push(chunk)); request.on('end', () => resolve(Buffer.concat(chunks))) })
    seen.push({ method: request.method, url: request.url, headers: request.headers, body })
    const send = (status, value) => { response.writeHead(status, { 'content-type': 'application/json' }); response.end(JSON.stringify(value)) }
    if (request.url === '/v1/snapshots') return send(201, { snapshotId: 'snapshot:mock' })
    if (request.url === '/v1/job-batches') return send(202, { jobs: [{ jobId: 'job:mock', candidateId: 'candidate:mock' }] })
    if (request.url === '/v1/jobs/job%3Amock/asset') return send(202, { state: 'QUEUED' })
    if (request.url === '/v1/jobs/job%3Amock/events?after=0') return send(200, { events: [{ sequence: 2, state: 'SETTLED' }] })
    if (request.url === '/v1/jobs/job%3Amock') return send(200, { jobId: 'job:mock', state: 'SETTLED' })
    if (request.url === '/v1/jobs/job%3Amock/result') return send(200, { jobId: 'job:mock', overlayRegions: [{ x: 1, y: 2, width: 3, height: 4, translation: 'Thật' }], modelReceipt: { resolvedModel: 'gemini-3.6-flash', modelMatched: true } })
    if (request.url === '/v1/series/bootstrap') return send(202, { glossarySnapshot: { id: 'series-glossary:series:mock', version: 1, hash: 'a'.repeat(64), entries: [] }, research: { state: 'not-consented' } })
    if (request.url === '/v1/series/series%3Amock/glossary') return send(200, { glossarySnapshot: { id: 'series-glossary:series:mock', version: 2, hash: 'b'.repeat(64), entries: [] }, research: { state: 'complete' } })
    return send(404, { error: { code: 'ROUTE_NOT_FOUND', message: 'Not found' } })
  })
  await new Promise((resolve) => server.listen(0, '127.0.0.1', resolve))
  t.after(() => server.close())
  const port = server.address().port
  const client = createBrokerClient({ endpoint: `http://127.0.0.1:${port}`, token: 'test-token', deviceId: 'desktop:test' })
  await client.registerSnapshot({ snapshotId: 'snapshot:mock' })
  const batch = await client.createBatch({ snapshotId: 'snapshot:mock', candidateIds: ['candidate:mock'] })
  await client.uploadAsset(batch.jobs[0].jobId, { bytes: png, contentType: 'image/png', sha256: sha256(png) })
  const events = await client.getEvents('job:mock', 0)
  const job = await client.getJob('job:mock')
  const result = await client.getResult('job:mock')
  const bootstrap = await client.bootstrapSeries({ seriesId: 'series:mock', title: 'Mock series', targetLanguage: 'vi', localContinuity: [], userCorrections: [], locallyObservedAliases: ['Mock series'] })
  const glossary = await client.getSeriesGlossary('series:mock')
  assert.equal(events.events[0].state, 'SETTLED')
  assert.equal(job.state, 'SETTLED')
  assert.equal(result.overlayRegions[0].translation, 'Thật')
  assert.equal(bootstrap.glossarySnapshot.version, 1)
  assert.equal(glossary.glossarySnapshot.version, 2)
  const upload = seen.find((entry) => entry.url.endsWith('/asset'))
  assert.equal(upload.headers['x-content-sha256'], sha256(png))
  assert.equal(upload.headers['content-type'], 'image/png')
  assert.equal(upload.headers.authorization, 'Bearer test-token')
  assert.equal(sniffImageType(upload.body), 'image/png')
  const bootstrapRequest = seen.find((entry) => entry.url === '/v1/series/bootstrap')
  assert.equal(bootstrapRequest.method, 'POST')
  assert.equal(JSON.parse(bootstrapRequest.body.toString('utf8')).seriesId, 'series:mock')
})
